### ISSUE TITLE
Make text highlightable

### ISSUE THREAD

**Issue by kavyasukumar** [voxmedia/lunchbox#3]

**Comment by caseymm** [comment]
Is this just for `quotable`? I don't think we needed it for twitter bug or factlist, but I can't quite remember.

**Comment by caseymm** [comment]
Coming along pretty well. Right now it only allows the user to highlight one contiguous fragment. Need to add the ability to allow for highlighting various sections/fragments.

**Comment by caseymm** [comment]
Need to fix a couple of javascript things and need to rework the highlight interaction.
